import { PersonalInfo, Project, Skill, Experience, Planet } from "@/app/types";

export const personalInfo: PersonalInfo = {
  name: "Jeonghо Dong",
  role: "Frontend Developer",
  tagline: "Crafting immersive web experiences with code and creativity",
  bio: `I'm a passionate frontend developer specializing in creating interactive and visually stunning web applications. With expertise in React, Next.js, and 3D web graphics, I transform ideas into engaging digital experiences.`,
  location: "Seoul, South Korea",
  email: "contact@example.com",
  github: "https://github.com/yourusername",
  linkedin: "https://linkedin.com/in/yourusername",
  audioUrl: "/audio/intro.mp3",
};

export const projects: Project[] = [
  {
    id: "1",
    title: "Boogie Boogie Crew",
    title_ko: "루돌프의 수족냉증을 막아줘",
    title_en: "Save Rudolph's Freezing Hooves",
    description: "Christmas-themed letter exchange service",
    description_ko: "크리스마스 시즌 타겟 편지 교환 서비스",
    description_en: "Christmas-themed letter exchange service for sharing warm messages",
    longDescription: "A service where users can send Christmas letters (socks) to their Rudolph during the Christmas season. Built with a team of 2 frontend developers and 1 designer, this service achieved 300 active users and handled 30,000 requests. Worked on both frontend interface implementation and backend server construction using NestJS.",
    longDescription_ko: "당시 프론트엔드 2명 / 디자이너 1명으로 구성된 팀입니다. 해당 서비스는 크리스마스 시즌을 타겟으로 한 나의 루돌프에게 주변 사람들에게 양말(편지)을 즉 크리스마스 기념 편지를 받는 서비스입니다. 백엔드와 프론트엔드 둘 다 작업을 진행하였고 해당 서비스로 실사용자 300명 30,000건의 트래픽을 받은 경험이 있습니다.",
    longDescription_en: "Built with a team of 2 frontend developers and 1 designer, this Christmas-themed service allows users to receive letters (socks) from friends for their Rudolph. Worked on both frontend and backend development, achieving 300 active users and handling 30,000 traffic requests during the Christmas season.",
    period: "2023.12 - 2024.01",
    teamSize: "Frontend 2, Designer 1",
    technologies: [
      "TypeScript",
      "Next.js",
      "React",
      "styled-components",
      "NestJS",
      "Nginx",
      "AWS (S3, CloudFront, Route53, Certificate Manager, EC2)",
    ],
    featured: true,
  },
  {
    id: "2",
    title: "NewsZap",
    title_ko: "뉴스잽",
    title_en: "NewsZap",
    description: "AI-powered news bias detection service",
    description_ko: "뉴스 편파성 감지 AI 서비스",
    description_en: "AI-powered service for detecting political bias in news articles",
    longDescription: "A service designed to reduce news bias by analyzing the political leanings of news articles. Using AI and keyword analysis, the system evaluates news topics and content to determine political orientation, presenting the results visually as numerical scores. This helps users make clearer judgments on political matters.",
    longDescription_ko: "해당 서비스는 뉴스의 편파성을 줄이기 위한 서비스입니다. 뉴스의 주제, 내용 등 다양한 요소를 AI 및 키워드로 기사의 정치적 성향을 판단 후 최종으로 수치를 시각적으로 나타냅니다. 정치적인 문제에 사용자들이 뚜렷한 판단을 할 수 있도록 도움을 주기 위해 시작하였습니다.",
    longDescription_en: "This service aims to reduce news bias by analyzing various elements such as news topics and content using AI and keywords to determine the political orientation of articles. The final bias score is visualized numerically to help users make clearer judgments on political issues.",
    period: "2024.05 - 2024.06",
    technologies: [
      "TypeScript",
      "Next.js",
      "Emotion",
      "Python",
      "Ollama AI",
      "Monorepo",
      "AWS (S3, CloudFront, Route53, Certificate Manager, EC2)",
    ],
    featured: true,
  },
  {
    id: "3",
    title: "3D Product Showcase",
    title_ko: "3D 제품 쇼케이스",
    title_en: "3D Product Showcase",
    description: "Interactive 3D product visualization platform",
    description_ko: "인터랙티브 3D 제품 시각화 플랫폼",
    description_en: "Interactive 3D product visualization platform",
    longDescription: "Built a cutting-edge e-commerce platform featuring real-time 3D product visualization using Three.js and React. Customers can interact with products in 3D space, customize colors, and view from any angle.",
    longDescription_ko: "Three.js와 React를 활용한 실시간 3D 제품 시각화를 특징으로 하는 최첨단 전자상거래 플랫폼을 구축했습니다. 고객은 3D 공간에서 제품과 상호작용하고, 색상을 커스터마이징하며, 모든 각도에서 볼 수 있습니다.",
    longDescription_en: "Built a cutting-edge e-commerce platform featuring real-time 3D product visualization using Three.js and React. Customers can interact with products in 3D space, customize colors, and view from any angle.",
    period: "2023.06 - 2023.09",
    technologies: [
      "React",
      "Three.js",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
    ],
    demoUrl: "https://demo.example.com",
    githubUrl: "https://github.com/example/project1",
    imageUrl: "/projects/project1.jpg",
    audioUrl: "/audio/project1.mp3",
    featured: false,
  },
  {
    id: "4",
    title: "Real-time Collaboration Tool",
    title_ko: "실시간 협업 도구",
    title_en: "Real-time Collaboration Tool",
    description: "Team collaboration platform with live updates",
    description_ko: "실시간 업데이트를 지원하는 팀 협업 플랫폼",
    description_en: "Team collaboration platform with live updates",
    longDescription: "Developed a real-time collaboration platform that enables teams to work together seamlessly. Features include live cursors, instant messaging, and collaborative whiteboard with WebSocket integration.",
    longDescription_ko: "팀이 원활하게 협업할 수 있도록 하는 실시간 협업 플랫폼을 개발했습니다. 실시간 커서, 즉각적인 메시징, WebSocket 통합을 통한 협업 화이트보드 기능을 포함합니다.",
    longDescription_en: "Developed a real-time collaboration platform that enables teams to work together seamlessly. Features include live cursors, instant messaging, and collaborative whiteboard with WebSocket integration.",
    period: "2023.01 - 2023.05",
    technologies: ["Next.js", "WebSocket", "Redis", "PostgreSQL", "Prisma"],
    demoUrl: "https://demo.example.com",
    githubUrl: "https://github.com/example/project2",
    imageUrl: "/projects/project2.jpg",
    audioUrl: "/audio/project2.mp3",
    featured: false,
  },
];

export const skills: Skill[] = [
  // Frontend
  { name: "React", category: "frontend", level: 5 },
  { name: "Next.js", category: "frontend", level: 5 },
  { name: "TypeScript", category: "frontend", level: 5 },
  { name: "JavaScript", category: "frontend", level: 5 },
  { name: "Three.js", category: "frontend", level: 4 },
  { name: "Framer Motion", category: "frontend", level: 4 },
  { name: "Tailwind CSS", category: "frontend", level: 5 },
  { name: "CSS/SCSS", category: "frontend", level: 5 },
  { name: "HTML5", category: "frontend", level: 5 },

  // Backend
  { name: "Node.js", category: "backend", level: 4 },
  { name: "Express", category: "backend", level: 4 },
  { name: "PostgreSQL", category: "backend", level: 3 },
  { name: "MongoDB", category: "backend", level: 3 },
  { name: "Prisma", category: "backend", level: 4 },
  { name: "GraphQL", category: "backend", level: 3 },

  // Tools
  { name: "Git", category: "tools", level: 5 },
  { name: "Docker", category: "tools", level: 3 },
  { name: "Webpack", category: "tools", level: 4 },
  { name: "Vite", category: "tools", level: 4 },
  { name: "Figma", category: "tools", level: 4 },
  { name: "Storybook", category: "tools", level: 4 },
];

export const experiences: Experience[] = [
  {
    company: "Tech Innovation Labs",
    position: "Senior Frontend Developer",
    period: "2022 - Present",
    description:
      "Leading frontend development for enterprise web applications. Implemented 3D visualization features and improved performance by 40%.",
    technologies: ["React", "Next.js", "Three.js", "TypeScript"],
  },
  {
    company: "Creative Digital Studio",
    position: "Frontend Developer",
    period: "2020 - 2022",
    description:
      "Developed interactive websites and web applications for various clients. Specialized in animation and user experience design.",
    technologies: ["React", "Vue.js", "Framer Motion", "GSAP"],
  },
  {
    company: "Startup Ventures",
    position: "Junior Frontend Developer",
    period: "2019 - 2020",
    description:
      "Built responsive web applications and maintained existing codebases. Collaborated with designers to implement pixel-perfect UIs.",
    technologies: ["JavaScript", "React", "Sass", "Bootstrap"],
  },
];

export const sectionAudios = {
  hero: "/audio/hero.mp3",
  about: "/audio/about.mp3",
  projects: "/audio/projects.mp3",
  skills: "/audio/skills.mp3",
  contact: "/audio/contact.mp3",
};

export const planets: Planet[] = [
  {
    id: "0",
    name: "Moon",
    name_ko: "달",
    size: 1.5,
    textureUrl: "/textures/planets/moon.jpg",
    position: [0, 2, 5],
    rotationSpeed: 0.002,
    environment: {
      groundColor: "#9a9a9a",
      skyColor: "#000000",
      fogColor: "#1a1a1a",
      ambientColor: "#ffffff",
      particleColor: "#888888",
      features: ["craters", "dust", "regolith"],
    },
  },
  {
    id: "1",
    name: "Mercury",
    name_ko: "수성",
    size: 1.8,
    textureUrl: "/textures/planets/mercury.jpg",
    position: [-18, 5, -15],
    rotationSpeed: 0.004,
    projectId: "1",
    environment: {
      groundColor: "#8a8a8a",
      skyColor: "#1a1a1a",
      fogColor: "#2a2a2a",
      ambientColor: "#ffffff",
      particleColor: "#cccccc",
      features: ["craters", "dust", "rocks"],
    },
  },
  {
    id: "2",
    name: "Venus",
    name_ko: "금성",
    size: 2.0,
    textureUrl: "/textures/planets/venus.jpg",
    position: [-8, -6, 10],
    rotationSpeed: 0.002,
    projectId: "2",
    environment: {
      groundColor: "#d4a574",
      skyColor: "#ff8c42",
      fogColor: "#ffa64d",
      ambientColor: "#ffcc99",
      particleColor: "#ffdd88",
      features: ["clouds", "volcanic", "haze"],
    },
  },
  {
    id: "3",
    name: "Earth",
    name_ko: "지구",
    size: 2.2,
    textureUrl: "/textures/planets/earth.jpg",
    position: [5, 3, -8],
    rotationSpeed: 0.003,
    projectId: "3",
    environment: {
      groundColor: "#4a7c4e",
      skyColor: "#87ceeb",
      fogColor: "#b0d4e8",
      ambientColor: "#ffffff",
      particleColor: "#88ff88",
      features: ["grass", "trees", "water"],
    },
  },
  {
    id: "4",
    name: "Mars",
    name_ko: "화성",
    size: 1.8,
    textureUrl: "/textures/planets/mars.jpg",
    position: [15, -4, 5],
    rotationSpeed: 0.003,
    projectId: "4",
    environment: {
      groundColor: "#c1440e",
      skyColor: "#e8a87c",
      fogColor: "#d4916a",
      ambientColor: "#ffccaa",
      particleColor: "#ff6644",
      features: ["rocks", "sand", "dust"],
    },
  },
  {
    id: "5",
    name: "Jupiter",
    name_ko: "목성",
    size: 3.0,
    textureUrl: "/textures/planets/jupiter.jpg",
    position: [20, 8, -20],
    rotationSpeed: 0.005,
    environment: {
      groundColor: "#d4a06a",
      skyColor: "#c4956a",
      fogColor: "#e8c4a0",
      ambientColor: "#ffddbb",
      particleColor: "#ffaa66",
      features: ["clouds", "storms", "gas"],
    },
  },
  {
    id: "6",
    name: "Saturn",
    name_ko: "토성",
    size: 2.8,
    textureUrl: "/textures/planets/saturn.jpg",
    position: [-15, -10, -25],
    rotationSpeed: 0.004,
    hasRing: true,
    ringTextureUrl: "/textures/planets/saturn_ring.png",
    environment: {
      groundColor: "#e8d4a0",
      skyColor: "#f4e8c4",
      fogColor: "#fff0d4",
      ambientColor: "#ffffee",
      particleColor: "#ffee88",
      features: ["rings", "clouds", "wind"],
    },
  },
  {
    id: "7",
    name: "Uranus",
    name_ko: "천왕성",
    size: 2.0,
    textureUrl: "/textures/planets/uranus.jpg",
    position: [12, -8, 18],
    rotationSpeed: 0.002,
    environment: {
      groundColor: "#64b5c4",
      skyColor: "#88d4e4",
      fogColor: "#a4e4f0",
      ambientColor: "#ccffff",
      particleColor: "#88ffff",
      features: ["ice", "fog", "crystals"],
    },
  },
  {
    id: "8",
    name: "Neptune",
    name_ko: "해왕성",
    size: 2.2,
    textureUrl: "/textures/planets/neptune.jpg",
    position: [-5, 12, -30],
    rotationSpeed: 0.002,
    environment: {
      groundColor: "#3464a4",
      skyColor: "#4488cc",
      fogColor: "#5599dd",
      ambientColor: "#aaddff",
      particleColor: "#66aaff",
      features: ["storms", "wind", "ice"],
    },
  },
];
